version: "3.9"
services:
  backend:
    build: ./backend
    container_name: gita-backend
    ports: ["8000:8000"]
    env_file: .env

  frontend:
    build: ./frontend
    container_name: gita-frontend
    ports: ["3000:3000"]
    depends_on: [backend]
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:8000/ask"
